---
spine:
  defaults:
    platform: cEOS
    bgp_as: 65002
    loopback_ipv4_pool: 192.168.201.0/24
    mlag: false
  nodes:
    - name: dc2-spine1
      id: 13
      mgmt_ip: 192.168.0.12/24
      evpn_route_servers: []

l3leaf:
  defaults:
    bgp_as: 65200-65298
    platform: cEOS
    loopback_ipv4_pool: 192.168.201.0/24
    vtep_loopback_ipv4_pool: 192.168.202.0/24
    uplink_interfaces: [Ethernet1]
    uplink_switches: [dc2-spine1]
    uplink_ipv4_pool: 192.168.203.0/24
    mlag_interfaces: [Ethernet3, Ethernet4]
    mlag_peer_ipv4_pool: 10.255.252.0/24
    mlag_peer_l3_ipv4_pool: 10.255.251.0/24
    virtual_router_mac_address: 00:1c:73:00:00:99
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384
    mlag: true
  node_groups:
    - group: mlag2
      bgp_as: 65299
      nodes:
        - name: dc2-leaf2a
          id: 3
          mgmt_ip: 192.168.0.15/24
          uplink_switch_interfaces: [Ethernet1]
        - name: dc2-leaf2b
          id: 4
          mgmt_ip: 192.168.0.16/24
          uplink_switch_interfaces: [Ethernet2]
