---
- name: Deploy Configurations
  hosts: FABRIC:CORE
  connection: local
  gather_facts: false
  tasks:
    - name: Deploy configurations and tags to CloudVision
      ansible.builtin.import_role:
        name: arista.avd.cv_deploy
      vars:
        cv_server: 192.168.0.5
        cv_username: cvpadmin
        cv_password: "cvp123!"
        cv_verify_certs: false
        cv_run_change_control: true
